[package]
name = "commander"
version = "0.1.0"
authors = ["Sean Toner <stoner@netflix.com>"]
edition = "2018"

[dependencies]
log = "0.4.8"
tokio = { path = "../../tokio/tokio", features = ["process"]} 
futures-util = "0.3.1"